[package]
name = "hamui"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"

[[example]]
name = "main"
crate-type = ["bin"]
